### ISSUE TITLE
Repeated exceptions

### ISSUE THREAD

**Issue by morberg** [alex3305/hass-components-debug#1]
I've been running this for a couple of hours in a docker image on MacOS. My log fills up with very many errors like this:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 173, in request
    result = await self._execute(api_commands)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 118, in _execute
    await self._observe(api_command)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 190, in _observe
    pr, r = await self._get_response(msg)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 109, in _get_response
    await self._reset_protocol(e)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 82, in _reset_protocol
    await protocol.shutdown()
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 133, in shutdown
    for exchange_monitor, cancellable in self._active_exchanges.values():
AttributeError: 'NoneType' object has no attribute 'values'
2018-12-01 17:44:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 99, in _get_response
    r = await pr.response
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 816, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 865, in _run
    blockresponse = yield from blockrequest.response
OSError: [Errno -1] Unknown error -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 173, in request
    result = await self._execute(api_commands)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 118, in _execute
    await self._observe(api_command)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 190, in _observe
    pr, r = await self._get_response(msg)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 109, in _get_response
    await self._reset_protocol(e)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 82, in _reset_protocol
    await protocol.shutdown()
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 133, in shutdown
    for exchange_monitor, cancellable in self._active_exchanges.values():
AttributeError: 'NoneType' object has no attribute 'values'
2018-12-01 17:44:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 99, in _get_response
    r = await pr.response
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 816, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 865, in _run
    blockresponse = yield from blockrequest.response
OSError: [Errno -1] Unknown error -1

During handling of the above exception, another exception occurred:
...
```
and then more of the same.

I have no idea what is going on, perhaps the errors mean more to you than me?

**Comment by morberg** [comment]
I am suspecting that the Flux component puts a lot of stress on the system and provokes errors a lot earlier.
