### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by morberg** [alex3305/hass-components-debug#2]
Pulled a version on December 7 and get this error:

```
2018-12-07 20:20:40 INFO (MainThread) [homeassistant.setup] Setting up logger
2018-12-07 20:21:07 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/service.py", line 277, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/app/homeassistant/components/light/tradfri.py", line 261, in async_turn_off
    await self._api(self._light_control.set_state(False))
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 163, in request
    result = await self._execute(api_commands)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 120, in _execute
    if api_command.observe:
AttributeError: 'NoneType' object has no attribute 'observe'
```

**Comment by alex3305** [comment]
Hi @morberg,

Thanks for testing. This issue is solved in 43e9d004fe270e0422491d48b209e3b008eea56e. It would be great if you could verify that, before closing this issue.

**Comment by morberg** [comment]
Haven’t seen this error in the latest version, looks like you fixed it. 

What I got last night was this:
```
2018-12-09 22:24:44 ERROR (MainThread) [coap] Exception CancelledError() can not be represented as errno, setting -1.
2018-12-09 22:24:44 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 102, in _get_response
    r = await pr.response
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 816, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 865, in _run
    blockresponse = yield from blockrequest.response
aiocoap.error.RequestTimedOut

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/service.py", line 277, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/app/homeassistant/components/switch/tradfri.py", line 100, in async_turn_off
    await self._api(self._socket_control.set_state(False))
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 166, in request
    result = await self._execute(api_commands)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 153, in _execute
    _, res = await self._get_response(msg)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 108, in _get_response
    raise RequestTimeout('Request timed out.', e)
custom_components.pytradfri.error.RequestTimeout: ('Request timed out.', RequestTimedOut())

**Comment by alex3305** [comment]
That seems just a request timeout. There is nothing I can really do about that.. It should also be in the latest Home Assistant version and not only this version.

Since the first issue is solved. I'm closing this issue. Should you encounter more issues, you can always open new ones :)
