### ISSUE TITLE
System hangs after 13 hours

### ISSUE THREAD

**Issue by morberg** [alex3305/hass-components-debug#6]
It took ~13 hours for my system to hang on 0.84.2, after which light states are no longer updated in HASS. Without this patch, the system hangs sooner so at least there's no degradation. The last error message I see is:
```
2018-12-16 16:54:40 ERROR (MainThread) [coap] Exception CancelledError() can not be represented as errno, setting -1.
2018-12-16 23:10:59 ERROR (SyncWorker_7) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiocoap/transports/tinydtls.py", line 160, in _run
    message = yield from self._queue.get()
  File "/usr/local/lib/python3.6/site-packages/aiocoap/util/asyncio.py", line 40, in get
    priority, first = yield from self._inner.get()
  File "/usr/local/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiocoap/transports/tinydtls.py", line 169, in _run
    self.coaptransport.new_error_callback(-1, self)
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 203, in _dispatch_error
    for key, (monitor, cancellable_timeout) in self._active_exchanges.items():
AttributeError: 'NoneType' object has no attribute 'items'
```
I also get a bunch of these warnings (only visible in the UI on `hass-server:8123/dev-info`, not visible in the log):
```
Sun Dec 16 2018 23:10:59 GMT+0100 (CET)

Observation deleted without explicit cancellation
```
The only thing non-standard with my installation is that I have enabled the Flux component.

**Comment by alex3305** [comment]
This is a Home Assistant issue. It is recursively calling the error method when an observation is reset.

Can you post how often the `Resetting Tradfri observations...` message is appearing in your logs?

**Comment by morberg** [comment]
I didn't see the `Resetting Tradfri observations...` in the logs at all, only in the web UI. That page seems to only show a fixed number of entries, none of which were `Resetting Tradfri observations...`.

FWIW I've now upgraded to 0.84.3 and see some other issues (will report separately).

**Comment by alex3305** [comment]
Cancellation should only happen when the event bus - and thus Home Assistant - is exited. You should also get a similar message with the standard pytradfri message.

I've dug through my log for the last three days (0.84.2) and I'm not seeing this issue. Maybe it's just a fluke? Can you try and pinpoint this issue further? Like when it happens? Why it happens on some lights, and some not?

**Comment by alex3305** [comment]
I'm closing both of your issues. If you have any new feedback or they have to be reopened, please let me know.
