### ISSUE TITLE
Errors with Hass 0.84.3

### ISSUE THREAD

**Issue by morberg** [alex3305/hass-components-debug#7]
Running Hass 0.84.3 I see many of these errors (didn't see them in 0.84.2). It seems to happen for most, but not all, lights in my setup. I haven't done any structured testing, figured I'll start with posting the messages here - it might be obvious to someone else what is going on.

```
2018-12-17 21:17:04 ERROR (MainThread) [coap] Exception CancelledError() can not be represented as errno, setting -1.
2018-12-17 21:17:04 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall light.turn_on (c:8acc6d858cdb41b2b91d0c4dd919bce5): entity_id=['light.tvsoffa'], color_temp=397, transition=30.0>
Traceback (most recent call last):
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 102, in _get_response
    r = await pr.response
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 816, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 865, in _run
    blockresponse = yield from blockrequest.response
aiocoap.error.RequestTimedOut

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1130, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/app/homeassistant/core.py", line 1143, in _execute_service
    await handler.func(service_call)
  File "/usr/src/app/homeassistant/components/light/__init__.py", line 270, in async_handle_light_on_service
    await light.async_turn_on(**pars)
  File "/usr/src/app/homeassistant/components/light/tradfri.py", line 334, in async_turn_on
    await self._api(command)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 166, in request
    result = await self._execute(api_commands)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 153, in _execute
    _, res = await self._get_response(msg)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 108, in _get_response
    raise RequestTimeout('Request timed out.', e)
custom_components.pytradfri.error.RequestTimeout: ('Request timed out.', RequestTimedOut())
```

I also get this error (again for most, but not all lights):
```
2018-12-17 21:18:38 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall light.turn_on (c:fe264efd7ff14c0cbd8900884458dae5): entity_id=['light.tvsoffa'], col
or_temp=398, transition=30.0>
Traceback (most recent call last):
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 102, in _get_response
    r = await pr.response
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 816, in _run_outer
    yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 865, in _run
    blockresponse = yield from blockrequest.response
OSError: [Errno -1] Unknown error -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1130, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/app/homeassistant/core.py", line 1143, in _execute_service
    await handler.func(service_call)
  File "/usr/src/app/homeassistant/components/light/__init__.py", line 270, in async_handle_light_on_service
    await light.async_turn_on(**pars)
  File "/usr/src/app/homeassistant/components/light/tradfri.py", line 334, in async_turn_on
    await self._api(command)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 166, in request
    result = await self._execute(api_commands)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 153, in _execute
    _, res = await self._get_response(msg)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 112, in _get_response
    await self._reset_protocol(e)
  File "/config/custom_components/pytradfri/api/aiocoap_api.py", line 84, in _reset_protocol
    await protocol.shutdown()
  File "/usr/local/lib/python3.6/site-packages/aiocoap/protocol.py", line 133, in shutdown
    for exchange_monitor, cancellable in self._active_exchanges.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by alex3305** [comment]
This seems to have something to do with your local installation? A bit like in #6 tbh. If your running a Pi, maybe your SD card is degrading, causing some lag and such issues?

I've yet have to update to 0.84.3, but I'm going to do that tonight. Thanks for the continious feedback!

**Comment by morberg** [comment]
I’m running in docker on a Mac Mini. Although hardware issues can’t be ruled out I would say it is unlikely. The mini is running other services that are working just fine.

**Comment by alex3305** [comment]
Could you test with the latest master branch? Also for your other issue.

**Comment by alex3305** [comment]
I've recently also encountered this issue. It happened when my Tradfri hub got a new IP address from DHCP. Maybe you can try and create a DHCP reservation for the Tradfri hub?

**Comment by morberg** [comment]
Sorry for not reporting back earlier, I have not been using HASS at all
because of too many issues. FWIW I already have a fixed IP on my gateway
since a couple of months.
